### ISSUE TITLE
Specify sharding for `jax.numpy.meshgrid`

### ISSUE THREAD

**Issue by pmocz** [jax-ml/jax#24332]
If there would be a way to simply specify sharding or devices for the output arrays of `jax.numpy.meshgrid()` (https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.meshgrid.html) so the output does not necessarily have the whole global array on each device, that would be awesome!

E.g.:

```python
import jax
import jax.numpy as jnp
from jax.experimental import mesh_utils
from jax.sharding import Mesh, PartitionSpec, NamedSharding

n_devices = jax.device_count()
mesh = Mesh(mesh_utils.create_device_mesh((n_devices, 1)), ("x", "y"))
sharding = NamedSharding(mesh, PartitionSpec("x", "y"))

N = 10000
xlin = jnp.linspace(0.0, 100.0, N)
X, Y = jnp.meshgrid(xlin, xlin, device=sharding)   # currently there is no `device=` option 
```

in the same fashion as how `jax.numpy.ones()` or `jax.numpy.array()` does it.

**Comment by jakevdp** [comment]
I don't think that `meshgrid` should have a `device` or `sharding` argument – `ones` and `array` have these because they are methods of creating an array from scratch. `meshgrid` on the other hand takes input arrays, processes them, and returns output arrays, so it seems reasonable that users would control input and output sharding the same way as with any function on arrays (some discussion in https://jax.readthedocs.io/en/latest/sharded-computation.html)

What do you think?

**Comment by pmocz** [comment]
Got it! So something like?

```python
sharded_meshgrid = jax.jit(jnp.meshgrid, out_shardings=sharding)
```

The paradigm not to specify sharding when a function takes arrays as input makes sense. In this function the input arrays are typically small and not distributed, while the outputs are huge and may need to be constructed in a distributed way to avoid running out of memory, so as long as that can be accomplished, it's all good!

**Comment by jakevdp** [comment]
Yeah that seems like the right approach when in an eager flow. Within `jit` you could use `with_sharding_costraint` for control, or you could annotate the input and output sharding for the overall function and let the compiler decide on the location for intermediate arrays.

**Comment by pmocz** [comment]
Thanks! I'll close the issue
