### ISSUE TITLE
hlo_helpers.dtype_to_ir_type is not complete comparing with jax.interpreters.mlir.dtype_to_ir_type

### ISSUE THREAD

**Issue by aws-qieqingy** [jax-ml/jax#24509]
Please:

- [ x ] Check for duplicate requests.
- [ x ] Describe your goal, and if possible provide a code snippet with a motivating example.

I noticed that the dtype look up table defined in https://github.com/jax-ml/jax/blob/main/jaxlib/hlo_helpers.py#L28 is missing dtypes comparing with the one in `jax.interpreters.mlir`: https://github.com/jax-ml/jax/blob/main/jax/_src/interpreters/mlir.py#L158. A few popular dtypes such as `bfloat16` is missing and it impacts the usability of. 

Is there any reason why we couldn't directly use `jax.interpreters.mlir.dtype_to_ir_dtype` in `hlo_helpers`?

**Comment by dfm** [comment]
Good questions! 

> Is there any reason why we couldn't directly use jax.interpreters.mlir.dtype_to_ir_dtype in hlo_helpers?

There is! since `hlo_helpers` is in `jaxlib` which is a separate package that `jax` depends on, it can't import from the `jax` namespace.

Can you expand a little bit more on the issue that you're seeing? You said:

> A few popular dtypes such as bfloat16 is missing and it impacts the usability of.

but I don't think you finished the sentence. Where is the usability problem? What operation are you trying to use and what error are you seeing?

The `jaxlib.hlo_helpers` and `jax.interpreters.mlir` APIs are both private, so they should typically be transparent to users. Perhaps you could provide more details about the problem and I can give some alternative suggestions!

**Comment by aws-qieqingy** [comment]
Thank you for the response. I found this problem when trying to call `hlo_helpers.hlo_const` with a numpy array of type `dtypes.bfloat16`, and it complains that it does not recognize the datatype. It hurts the usability of `hlo_const` at the very least.

**Comment by hawkinsp** [comment]
Sure, but the question remains: why are you using `hlo_helpers` at all? It's a private module.

**Comment by hawkinsp** [comment]
(We're trying to encourage everyone to migrate to the newer JAX FFI, fwiw: https://jax.readthedocs.io/en/latest/ffi.html )

**Comment by aws-zhehongb** [comment]
we are building extensions of JAX by introducing our own jax primitives. we call functions from `jaxlib.hlo_helpers` and `jax.interpreters.mlir` in the lowering rule for our primitives. We found that `jaxlib.hlo_helpers` and `jax.interpreters.mlir` has overlapped functionality. 

I wonder what are the high-level guidance on when to use  `jaxlib.hlo_helpers` vs `jax.interpreters.mlir`. 

also any plan to unify these two?

**Comment by dfm** [comment]
The high level recommendation would be to avoid using _either_ of these modules if possible. It's best to combine [the FFI](https://jax.readthedocs.io/en/latest/ffi.html) (for external library calls) with public APIs like `jax.custom_jvp` or `jax.custom_vjp` for customizing behaviors under transformations. If there is a use case that isn't covered by these public APIs, please let us know and I'm always happy to provide guidance. It's a high priority for me to support these kinds of extensions.

> I wonder what are the high-level guidance on when to use jaxlib.hlo_helpers vs jax.interpreters.mlir.

If you can't use public APIs for your needs, I'd probably recommend using `jax.interpreters.mlir` with the understanding that it can change at any time without compatibility guarantees, and we don't formally support such use cases.

> also any plan to unify these two?

I don't think that's likely! I think that `jaxlib.hlo_helpers` will probably disappear at some point, but it'll still be a while before that happens.

**Comment by aws-zhehongb** [comment]
We are lowering our jax primitives to a custom call (by doing `mlir.register_lowering(xxx, xxx_lowering_rule, platform="neuron")`). We are calling things like `jaxlib.hlo_helpers.custom_call`.

> I'd probably recommend using jax.interpreters.mlir with the understanding that it can change at any time without compatibility guarantees, and we don't formally support such use cases.

This sounds good, thanks
`

**Comment by dfm** [comment]
Makes sense. I will say that `jax.extend.ffi.ffi_call` should support everything that a custom primitive does (with some small caveats around customization under function transformations for now) with far less boilerplate. I'd recommend checking it out instead of writing your own primitives!

I'm going to close this issue as solved for now, but please open other issues if you run into problems.
