### ISSUE TITLE
Missing `jax.core.ConcreteArray` in v0.4.36: Migration Guide and API Stability Concerns

### ISSUE THREAD

**Issue by daskol** [jax-ml/jax#25314]
### Description

Could you please point me to a migration guide for updating from JAX v0.4.35 to v0.4.36? Specifically, I’m looking for guidance on handling significant changes or removals of publicly exported symbols, such as `jax.core.ConcreteArray`, which appears to have been removed in the latest release. 

For my research purposes, I extend JAX in specific ways and rely on its public primitive/interpreter API. This reliance makes breaking changes in publicly exported symbols particularly impactful. How can such issues be better anticipated or prevented in the future?

### Context

The [nightly CI tests][ci] for my [daskol/yax][1] project started failing with the release of JAX v0.4.36. Upon investigation, it seems that the issue is caused by the absence of `jax.core.ConcreteArray`, which was available in earlier versions. 

The [v0.4.36 changelog][2] notes a number of breaking changes, but I couldn’t find detailed instructions or migration steps for this specific case. 

### Links

- Affected Project: [daskol/yax][1]  
- Changelog Reference: [v0.4.36 changelog][2]  
- Failing CI Job: [Nightly Testing Logs][ci]  

[1]: https://github.com/daskol/yax
[2]: https://github.com/jax-ml/jax/releases/tag/jax-v0.4.36
[ci]: https://github.com/daskol/yax/actions/runs/12194083414/job/34017355642

### System info (python version, jaxlib version, accelerator, etc.)

New JAX release v0.4.36 (see nightly CI [workflow][ci]).

[ci]: https://github.com/daskol/yax/actions/runs/12194083414/job/34017355642

**Comment by dfm** [comment]
Good question! We don't actually have a migration guide for the use of `jax.core` since that is considered internal private API as described in our API compatibility docs: https://jax.readthedocs.io/en/latest/api_compatibility.html

While these APIs typically do stay stable over long periods, we make no guarentees, and this particular release included several major refactors (especially https://github.com/jax-ml/jax/commit/c36e1f7c1ad4782060cbc8e8c596d85dfb83986f), so it'll be particularly painful for these kinds of use cases. It looks like `ConcreteArray` was removed in https://github.com/jax-ml/jax/pull/24640, so perhaps you can take a look at that change for tips on migration in your codebase.

Hope this helps!

**Comment by daskol** [comment]
> ### What is not covered?
> - jax.core
> - jax.interpreters
> - jax.extend
>
> This list is not exhaustive.

The situation feels even more concerning than I initially thought. 😞

Is there a roadmap, set milestones, or a timeline for breaking changes? This feels like a paradox: on one hand, JAX aligns with Google's internal goals; on the other, it’s fostering an open-source community and ecosystem.

Without any stability guarantees, maintaining side projects and adapting to continuous changes in JAX is becoming increasingly challenging. I’d like to point out that it takes a significant amount of time to read through and fully understand all the extensive commits and changes. Any form of roadmap, stability milestones, or even high-level guidance on upcoming breaking changes would go a long way toward helping the community plan and manage their projects more effectively.

**Comment by dfm** [comment]
(FWIW, I should note that when I said "internal", I definitely didn't mean "internal to Google", I meant "internal to the JAX project"! There are actually strict Google policies that disallow the downstream use of these APIs.)

But, the point of the [compatibility doc](https://jax.readthedocs.io/en/latest/api_compatibility.html) is to describe exactly what kinds of compatibility guarantees should be expected from the project, and we try to maintain good stability and coverage on the whole public API surface. There are plans to publish project roadmaps, but I don't anticipate that these would cover things like the APIs in `jax.core`.

Other team or community members should feel free to chime in, but I would say that given the guidelines from the API compatibility doc, the best way for downstream users of JAX to ensure compatibility across releases is to not rely on features that aren't exposed via public APIs. Of course, I know that that's not always possible (in a past life I actually maintained several open source projects that depended on JAX internals :D), and in those cases, we want to hear about what features are missing so that we can try to provide stable support. Then, if your project still requires the use of internal APIs, it might be worth adding a CI test against [JAX nightly](https://jax.readthedocs.io/en/latest/installation.html#jax-nightly-installation) to identify issues early and report them upstream here.

I know that breakages caused by dependency changes are frustrating, and we do care about maintaining compatibility where we can!

**Comment by dougalm** [comment]
let us know if you need any advice on migrating away from ConcreteArray. `jax._src.core.to_concrete_array` replaces some of the functionality. Of course, we reserve the right to break that too in the future.
