### ISSUE TITLE
jax.checkpoint prevents id_tap from running

### ISSUE THREAD

**Issue by sbodenstein** [jax-ml/jax#5134]
This should, but doesn't print:
```
import jax
from jax.experimental import host_callback

@jax.checkpoint
def f(x):
  host_callback.id_tap(print, x)
  return x

jax.grad(f)(2.)
```
It does print if either:
- `@jax.checkpoint` is removed
- the output of host_callback is used

**Comment by gnecula** [comment]
The best way to use `id_tap` is to use its result. This fits best with the functional nature of JAX, because internally JAX is not aware that `id_tap` has side-effects. This can make JAX sometime eliminate the operation as it appears to not be needed. This seems to happen during the analysis that is part of implementing `jax.checkpoint`. If you add a `jax.make_jaxpr` you will see that the `jax.grad(f)` is the constant function `lambda _: 1.`. 

If you use the result of `id_tap` then you will also be able to print the cotangent of the output.

**Comment by sbodenstein** [comment]
The [documentation states that](https://github.com/google/jax/blob/master/jax/experimental/host_callback.py#L45):
> As of September 2020, it is not necessary anymore for the results of the tap to be used in the rest of the computation. The tap function will execute based on program order. 
If this is correct, then surely JAX must be aware that `id_tap` has side-effects, and cannot simply eliminate it if it wants?

**Comment by gnecula** [comment]
I will add a caveat to the documentation.

**Comment by gnecula** [comment]
I have clarified the documentation: id_tap that does not use its results may be eliminated by partial evaluation; if in doubt, use the result. Perhaps a better solution is possible, to make JAX aware of side-effects, but right now that seems a low priority.

**Comment by gnecula** [comment]
I have re-opened this issue, we should try to fix this.

**Comment by hawkinsp** [comment]
id_tap is removed from JAX, so this issue should be moot.
